config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  #resources :articles
  resources :articles do
    resources :comments
  end
 
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
  #validates :title, presence: true, length: { minimum: 5 }
  def expire_date
  	created_at.next_month.to_date
  end
  def remaining_days
    expired? ? 0 : (Date.today - expire_date).to_i
  end

  def expired?
  	puts expire_date
    (Date.today - expire_date).to_i > 0   
  end

  def expired_today?
    Date.today == expire_date
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
#ApplicationController
  http_basic_authenticate_with name: "admin", password: "123qweasd", except: [:index, :show]

  def index
    #@articles = Article.all
    @articles = Article.paginate(page: params[:page], per_page: 2)
  end

  def new
    #@article = Article.find(params[:id])
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def show
    @article = Article.find(params[:id])
  end

  def create
  	@article = Article.new(article_params)
 
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

    def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private
    def article_params
      params.require(:article).permit(:title, :text)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "123qweasd", only: :destroy

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/articles/edit.html.erb
<div class="row" style="padding-top:10%;">
  <div class="col"></div>
    <div class="col-md-7">
      <h1>Edit article</h1>
      <%= form_with(model: @article, local: true) do |form| %>

      <% if @article.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@article.errors.count, "error") %> prohibited
            this article from being saved:
          </h2>
          <ul>
            <% @article.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <p>
        <%= form.label :title %><br>
        <%= form.text_field :title, class: 'form-control'%>
      </p>

      <p>
        <%= form.label :text %><br>
        <%= form.text_area :text, class: 'form-control'%>
      </p>

      <p>
        <%= form.submit class:'btn btn-md btn-success'%>
      </p>

      <%= link_to 'Regresar', articles_path, class:'btn btn-md btn-info'%>
      <%= link_to 'Inicio', welcome_index_path, class:'btn btn-md btn-primary'%>

    </div>
  <div class="col"></div>
</div>  
<% end %> 

app/views/articles/index.html.erb
<div class="row">
  <div class="col"></div>
    <div class="col-md-10">

      <h1>Lista de articulos</h1>
      <p>
        <%= link_to 'Crear nuevo articulo', new_article_path, class:'btn btn-lg btn-info'%>
      </p>
      <table class="table table-hover">
        <tr>
          <th>Title</th>
          <th>Text</th>
          <th></th>
        </tr>
 
      <% @articles.each do |article| %>
          <tr>
            <td><%= article.title %></td>
            <td><%= article.text %></td>

            <td><%= link_to 'Ver', article_path(article), class:'btn btn-lg btn-info'%></td>
            <td><%= link_to 'Editar', edit_article_path(article), class:'btn btn-lg btn-warning'%></td>
            <td><%= link_to 'Eliminar', article_path(article), class:'btn btn-lg btn-danger',
                    method: :delete,
                    data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </table>
      <%= will_paginate @posts, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, previous_label: 'Anterior', next_label: 'Siguiente', inner_window: 1, outer_window: 0 %>
      <%= link_to 'Inicio', welcome_index_path, class:'btn btn-md btn-primary' %>
    </div>
  <div class="col"></div>
</div>

app/views/articles/new.html.erb
<div class="row" style="padding-top:10%;">
  <div class="col"></div>
    <div class="col-md-7">

      <%= form_with scope: :article, url: articles_path, local: true do |form| %>
  
      <% if @article.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@article.errors.count, "error") %> prohibited
            this article from being saved:
          </h2>
          <ul>
            <% @article.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <h1>New article</h1>
      <p>
        <%= form.label :title %>
        <br>
        <%= form.text_field :title, class: 'form-control' %>
      </p>
 
      <p>
        <%= form.label :text %>
        <br>
        <%= form.text_area :text, class: 'form-control'%>
      </p>
 
      <p>
        <%= form.submit class:'btn btn-md btn-success'%>
      </p>
      <%= link_to 'Regresar', articles_path, class:'btn btn-md btn-info'%>
      <%= link_to 'Inicio', welcome_index_path, class:'btn btn-md btn-primary' %>
    </div>
  <div class="col"></div>
</div>  
<% end %>

app/views/articles/show.html.erb
<div class="row">
  <div class="col"></div>
    <div class="col-md-7">
      <p id="article_title">
        <strong>Titulo:</strong>
        <%= @article.title %>
      </p>
 
      <p>
        <strong>Texto:</strong>
        <%= @article.text %>
      </p>
 
      <h2>Comentarios</h2>
      <%= render @article.comments %>
      
      <h2>Agregar comentario:</h2>
      <%= render 'comments/form' %>
      <p>
        <%= link_to 'Editar', edit_article_path(@article), class: "btn btn-md btn-info" %>
        <%= link_to 'Regresar', articles_path, class: "btn btn-md btn-primary" %>
      </p>
    </div>
  <div class="col"></div>
</div>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Eliminar Comentario', [comment.article, comment],
               class: "btn btn-md btn-danger",
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
  <%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
    <div class="field" style="100;">
    <p>
      <%= form.label :commenter %><br>
      <%= form.text_field :commenter, class: 'form-control'%>
    </p>
    <p>
      <%= form.label :body %><br>
      <%= form.text_area :body, class: 'form-control'%>
    </p>
    <p>
      <%= form.submit class: "btn btn-md btn-success" %>
    </p>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mi Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navigation' %>
    <div class="container">
      <%= yield %>      
    </div>
  </body>
</html>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="https://getbootstrap.com/docs/4.3/examples/navbar-fixed/#">Blog Jorge</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link"><%= link_to 'Home', welcome_index_path, class:"nav-link"%></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link"><%=link_to 'Blog', articles_path, class:"nav-link"%></a>
      </li>
    </ul>
    <form class="form-inline mt-2 mt-md-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/welcome/index.html.erb
<div class="row" style="padding-top:10%;">
  <div class="col"></div>
    <div class="col-md-7 text-center">
      <h1>Hola, Bienvenido a mi Blog</h1>
      <%= link_to 'Mi Blog', articles_path, class:'btn btn-lg btn-success'%>
    </div>
  <div class="col"></div>
</div>